# 1. Ligação à Base de Dados (Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/news_scraper_db
spring.datasource.username=utilizador_java
spring.datasource.password=minha_password_123
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Configuração do Hibernate (A Magia)
# 'update' faz com que o Spring crie as tabelas sozinho se não existirem
spring.jpa.hibernate.ddl-auto=update
# Mostra no terminal o SQL que o Java está a executar (bom para aprender)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true